spring:

# ****************************服务端口****************************
server:
  port: 6010

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
    me.chanjar.weixin.mp.*: debug
  path: /log/spring-alibaba/wxmp

# ****************************系统端口管理****************************
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# ****************************微信公众号配置****************************
wx:
  mp:
    appId : wx67c700ed4fe84c30
    secret : 3fa174915df42b21309efaa99255b39c
    token : 123456
    aesKey :
# 存储配置redis(可选)
#    config-storage:
#      type : redis
#      redis:
#        host : 192.168.44.78
#        port : 6379
