# *****************************服务端口*****************************
server:
  port: 18002
# *****************************服务注册*****************************
spring:
  cloud:
    nacos:
      discovery:
        server-addr: guyw.top:20080
        ip: 192.168.10.55
# *****************************开启所有请求端点*****************************
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.lanswon.*: debug
    com.alibaba.nacos.client.*: error
    com.alibaba.nacos.client.config.impl.ClientWorker: error
  path: /log/spring-alibaba/admin