# *****************************服务端口*****************************
server:
  port: 18002
# *****************************服务注册*****************************
spring:
  application:
    name: cloud-admin
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.78:8848
# *****************************开启所有请求端点*****************************
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    com.lanswon.*: debug
  path: /log/spring-alibaba/admin