# *****************************服务端口*****************************
server:
  port: 18001

spring:
  application:
    name: cloud-gateway
  # *****************************链路调用*****************************
  zipkin:
    base-url: http://192.168.44.78:9411
    sender:
      type: web
  sleuth:
    sampler:
      # 采样100%
      probability: 1.0
  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.78:8848
        # 多网卡指定客户端IP
        ip: 172.1.1.244
    # *****************************网关*****************************
    gateway:
      # 找不到service实例，默认返回503 改为404
      loadbalancer:
        use404: true
      discovery:
        locator:
          lower-case-service-id: true
          # 让网关通过服务发现组件找到其他微服务
          enabled: true
      routes:
        - id: CLOUD-UUM
          uri: lb://CLOUD-UUM
          predicates:
          - Path=/way/**
          - CustomizeBetween= 上午10:00,下午5:00
          filters:
          - StripPrefix= 1
        - id: content-center
          uri: lb://content-center
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix= 1
# *****************************开启所有请求端点*****************************
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    com.lanswon.*: debug
  path: /log/spring-alibaba/gateway