# *****************************服务端口*****************************
server:
  port: 18001

spring:
  application:
    name: cloud-gateway

  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: guyawei.top:8848

    # *****************************网关*****************************
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          # 让网关通过服务发现组件找到其他微服务
          enabled: true
      routes:
        - id: CLOUD-UUM
          uri: lb://CLOUD-UUM
          predicates:
          - Path=/way/**
          filters:
          - StripPrefix= 1

# *****************************开启所有请求端点*****************************
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always