# *****************************服务端口*****************************
server:
  port: 18001

spring:
  application:
    name: cloud-gateway

  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.78:8848

    # *****************************网关*****************************
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: content-center
          uri: lb://content-center
          predicates:
          - Path=/way/**
          filters:
          - StripPrefix= 1
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackuri: forward:/fallback

# *****************************开启所有请求端点*****************************
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always