spring:
  session:
    store-type: none
  # ******************************数据源******************************
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_security?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid
  security:
    user:
      name: user
      password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/static/

server:
  port: 8060
  servlet:
    session:
      timeout: 10

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
    org.springframework.security.*: info
  path: /log/spring-alibaba/auth-demo

# ****************************系统端口管理****************************
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ****************************mybatis映射****************************
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml

lanswon:
  security:
    #browser:
      #loginPage: /demo-signIn.html
    code:
      image:
        length: 4
        width: 100
        #url: /user
    browser:
      #loginPage: /nrsc-login.html
      loginType: JSON
      signUpUrl: /demo-signUp.html
      #signOutUrl: /nrsc-logout.html
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4

      filterProcessesUrl: /qqLogin


