spring:
  session:
    store-type: redis
  redis:
    port: 6379
    host: 192.168.44.78  #106.15.235.215
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
#    sentinel:
#      master: mymaster
#      nodes: 192.168.44.78:16379
  # ******************************数据源******************************
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_security?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid
  security:
    user:
      name: user
      password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/static/

server:
  port: 8061
  servlet:
    session:
      timeout: 10

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
    org.springframework.security.*: info
  path: /log/spring-alibaba/auth-demo

# ****************************系统端口管理****************************
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ****************************mybatis映射****************************
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml

lanswon:
  security:
    #browser:
      #loginPage: /demo-signIn.html
    code:
      image:
        length: 4
        width: 100
        #url: /user
    browser:
      loginType: JSON
      signUpUrl: /demo-signUp.html
      #signOutUrl: /nrsc-logout.html
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wx67c700ed4fe84c30
        app-secret: 3fa174915df42b21309efaa99255b39c
      filterProcessesUrl: /qqLogin
    oauth2:
      clients:
        - clientId: lanswon
          clientSecret: 123456
          accessTokenValiditySeconds: 3600


#security:
#  oauth2:
#    client:
#      client-id: lanswon
#      client-secret: 123456
#      registered-redirect-uri: http://example.com