spring:
  application:
    name: user-center
  # ****************************数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_center?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid
  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.78:8848  #不需要协议
        #namespace: 1b3bc369-e9c8-4208-8f2e-63993378a986
        cluster-name: china
        metadata:
          version: v1
    # *****************************消费者配置stream-rocketMQ*****************************
    stream:
      rocketmq:
        binder:
          name-server: 192.168.44.78:9876
      bindings:
        intput:
          destination: stream-add-bonus
          group: stream-user-group #如果用的是rocketMQ必须要设置，其他的MQ可以留空

# ****************************消费者rocketMQ配置,使用stream可以不配置****************************
rocketmq:
  name-server: 192.168.44.78:9876


# ****************************服务端口****************************
server:
  port: 8011

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
  path: /log/spring-alibaba/usercnter

# ****************************系统端口管理****************************
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ****************************mybatis映射****************************
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml

