spring:
  # ******************************Boot Admin 客户端******************************
#  boot:
#    admin:
#      client:
#        url: http://192.168.10.55:18002
  # ****************************数据源*****************************
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_center?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid
  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.78  #不需要协议
        # namespace: 1b3bc369-e9c8-4208-8f2e-63993378a986
        cluster-name: lanswon
        metadata:
          version: v1
    # *****************************消费者配置stream-rocketMQ*****************************
    stream:
      rocketmq:
        binder:
          name-server: 192.168.44.78:9876
      bindings:
        input:
          # 如果用的是rocketMQ必须要设置，其他的MQ可以留空
          group: stream-user-group
          destination: stream-add-bonus
  # *****************************链路调用*****************************
  zipkin:
    base-url: http://192.168.44.78:9411
    sender:
      type: web
  sleuth:
    sampler:
      # 采样100%
      probability: 1.0

# ****************************消费者rocketMQ配置,使用stream可以不配置****************************
rocketmq:
  name-server: 192.168.44.78:9876


# ****************************服务端口****************************
server:
  port: 8012

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
    com.alibaba.nacos.*: error #使用Stream-rocketmq包时会一致打印naocs心跳日志，所以调整日志级别
  path: /log/spring-alibaba/usercnter

# ****************************系统端口管理****************************
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ****************************mybatis映射****************************
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml

