spring:
  application:
    name: content-center
  # ******************************数据源******************************
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/content_center?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid
  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: guyawei.top:8848
        #指定 namespace
        #namespace: 1b3bc369-e9c8-4208-8f2e-63993378a986
        #指定 集群名称
        cluster-name: lanswon
        #ribbon 实现元数据版本控制
        metadata:
          # 当前版本
          version: v1
          # 允许调用的版本
          target-version: v1
    # *****************************服务容错限流*****************************
    sentinel:
      transport:
        # 连接sentinel控制台
        dashboard: guyawei.top:9999
        heartbeat-interval-ms: 5000
        # 指定客户端连接ip
        client-ip: 172.1.1.244
        # 指定客户端连接端口
        port: 8720
      log:
        dir: /log/spring-alibaba/content-center/csp
      #提前触发 Sentinel 初始化
      eager: true
    # *****************************生产者配置stream-rocketMQ*****************************
    stream:
      rocketmq:
        binder:
          name-server: guyawei.top:9876
        # stream 配置事务消息 需要注意
        bindings:
          output:
            producer:
              transactional: true
              group: tx-content-group

      bindings:
        output:
          # topic 目的地
          destination: stream-add-bonus

# *****************************注解@sentinelRestTemplate功能开关****************************
resttemplate:
  sentinel:
    enabled: true

# ****************************生产者rocketMQ配置,使用stream可以不配置****************************
rocketmq:
  name-server: guyawei.top:9876
  producer:
    # 必须指定group
    group: content-group

# ****************************配置的方式使用负载均衡策略，比代码的方式优先级更高****************************
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


# ****************************开启ribbon饥饿加载****************************
ribbon:
  eager-load:
    enabled: true
    clients: user-center

# ****************************开启feign日志级别及配置****************************
feign:
  #整合sentinel
  sentinel:
    enabled: true
  client:
    config:
      #微服务实例
      user-center:
        loggerLevel: full
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    #让feign 使用apache httpclient 做请求；而不是默认url
    enabled: true
  #开启请求压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true

# ****************************服务端口****************************
server:
  port: 8010

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
    ribbonConfig.*: debug
    com.alibaba.nacos.*: error #使用Stream-rocketmq包时会一致打印naocs心跳日志，所以调整日志级别
  path: /log/spring-alibaba/content-center

# ****************************系统端口管理****************************
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ****************************mybatis映射****************************
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml

