# *****************************服务端口*****************************
server:
  port: 8060


spring:
  # *****************************链路调用*****************************
#  zipkin:
#    base-url: http://192.168.44.78:9411
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      # 采样100%
#      probability: 1.0

  # ******************************数据源******************************
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_security?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid
  # ******************************redis******************************
  redis:
    timeout: 5000
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 0
    port: 6379
    host: 192.168.44.78
#      sentinel:
#      master: mymaster
#      nodes: 192.168.44.78:16379  #192.168.254.129:16379
#  application:
#    name: CLOUD-AUTHSERVER
  # *****************************服务注册*****************************
  cloud:
    nacos:
      discovery:
        server-addr: jaswine.top:18848
        # 多网卡指定客户端IP
#        ip: 172.1.1.239
  # *****************************mvc配置*****************************
  mvc:
    view:
      prefix: /
      suffix: .html
    resources:
      static-locations: classpath:/static/
# *****************************开启所有请求端点*****************************
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# ****************************系统日志****************************
logging:
  level:
    com.lanswon.*: debug
    org.springframework.security.*: info
    io.lettuce.core.protocol.*: debug
  path: /log/spring-alibaba/auth-server

# ****************************开启feign日志级别及配置****************************
feign:
  client:
    config:
      #微服务实例
      CLOUD-UUM:
        loggerLevel: full
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    #让feign 使用apache httpclient 做请求；而不是默认url
    enabled: true
    #开启请求压缩
    compression:
      request:
        enabled: true
      response:
        enabled: true



lanswon:
  security:
    code:
      image:
        length: 4
        width: 60
        height: 38
    browser:
      loginType: JSON
      loginPage: /imooc-signIn.html
    social:
      qq:
        app-id:
        app-secret:
        providerId: callback.do
      weixin:
        app-id:
        app-secret:
      filterProcessesUrl: /qqLogin
    oauth2:
      clients:
        - clientId: liyuan
          clientSecret: 123456
          accessTokenValiditySeconds: 21600
        - clientId: lanswon
          clientSecret: 123456
          accessTokenValiditySeconds: 21600

